/*
 * ASSEMBLY Parser main file
 */

/*
 * parses the assmebly file generated by "objdump" util of Linux
 */

#include "main.h"

FILE *asm_file;
char *ip_file_name = NULL;

int main(int argc, char *argv[])
{
	printf("\n<<<<<<<<<<<< Assembly Parser >>>>>>>>>>>>\n\n");

/* initialization */
	if(proc_init() != TRUE)
	{
		printf("process initialization failed\n");
			exit(0);
	}

/* file reading */
	if(argc != 2)
	{
		printf(" Please enter one instruction file\n");
	}
	else
	{
		printf("processing file '%s' ...\n",argv[1]);
	}
	asm_file = fopen(argv[1], "r");
	ip_file_name = argv[1];

/* ASM parser */
	if(mnemonic_parser() != TRUE)
	{
		debug_print("Assembly parser failed\n",0);
			exit(0);
	}

/* close the file */
	fclose(asm_file);
	printf("done\n");

	return TRUE;
}
